/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-surface-variant": "#bac9cc",
          "on-secondary": "#003911",
          "inverse-surface": "#dce2f6",
          "secondary-container": "#05b046",
          "surface-container-low": "#151b2a",
          "error-container": "#93000a",
          "tertiary-fixed-dim": "#ffb4aa",
          "on-error": "#690005",
          "surface-container-high": "#232a39",
          "primary": "#c3f5ff",
          "background": "#0c1321",
          "secondary-fixed-dim": "#53e16f",
          "secondary-fixed": "#72fe88",
          "tertiary-fixed": "#ffdad5",
          "on-error-container": "#ffdad6",
          "on-surface": "#dce2f6",
          "tertiary": "#ffe8e4",
          "on-secondary-fixed": "#002107",
          "on-primary": "#00363d",
          "primary-fixed-dim": "#00daf3",
          "on-secondary-fixed-variant": "#00531c",
          "outline": "#849396",
          "surface-container-lowest": "#070e1c",
          "surface-variant": "#2e3544",
          "primary-fixed": "#9cf0ff",
          "error": "#ffb4ab",
          "surface-bright": "#323949",
          "surface": "#0c1321",
          "outline-variant": "#3b494c",
          "on-primary-fixed-variant": "#004f58",
          "inverse-primary": "#006875",
          "on-primary-container": "#00626e",
          "surface-tint": "#00daf3",
          "on-tertiary": "#690003",
          "inverse-on-surface": "#2a3040",
          "primary-container": "#00e5ff",
          "surface-dim": "#0c1321",
          "tertiary-container": "#ffc2ba",
          "on-background": "#dce2f6",
          "secondary": "#53e16f",
          "on-primary-fixed": "#001f24",
          "surface-container": "#19202e",
          "on-tertiary-fixed-variant": "#930005",
          "on-tertiary-container": "#b60009",
          "surface-container-highest": "#2e3544",
          "on-tertiary-fixed": "#410001",
          "on-secondary-container": "#003a11",
          "vibrant-orange": "#FF9500"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "fontFamily": {
          "headline": ["Space Grotesk"],
          "body": ["Inter"],
          "label": ["Inter"],
          "mono": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
}
